from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### include rules #####


include: "rules/flatten.smk"
include: "rules/quantify.smk"
include: "rules/common.smk"

if config["download"]:

    include: "rules/ref.smk"

if config["spike_in"]:

    include: "rules/spike.smk"
    include: "rules/combine.smk"




##### target rules #####

rule all:
    input:
        get_target_input()