######## Parameters you MUST set #########

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release 
  release: 108
  # Genome build
  build: GRCh38


spike_in: True

# If spike-in set to True, must fill in species, release, and build for spike-in
spike: 
  # Ensembl species name
  species: drosophila_melanogaster
  # Ensembl release
  release: 108
  # Genome build
  build: BDGP6



  ####### PARAMETERS YOU SHOULD CHECK ########

  